### PR TITLE
Add learning objectives to Week 10

### PR DESCRIPTION
**Pull request by AndreaDeMott**

### CODE REVIEW

**Comment by JoshCheek** [comment]
Can you turn these into tests and add them to https://github.com/JoshCheek/challenges If you want it on the CodePlatoon organization, then you can fork the repository to here, but pls send improvements back upstream. I added a [license](https://github.com/JoshCheek/challenges/blob/0bd71030a74bdc81b64592cfa02707e48f6c0ed3/License.md) to facilitate such use cases.

**Comment by AndreaDeMott** [comment]
Hi Josh,  I need a little more clarification before I can do this:

about turning these into tests:
I’m not clear on what kind of “tests” are these going to be.  If I’m just
writing a Ruby testing class (e.g. "class AcceptanceTest < Minitest::Test
etc etc…")  I need to define a context for what is being tested.  In other
words, if the students will be testing a Ruby application, what does the
application do?  (what is the “whiteboard” or “user story” it is wrapped
into?)

I have been searching for some practice problems that would fit these
learning objectives well (e.g. on Ada Developer Academy or Odin Project).
None of these sites give just bare-bones tests.

about forking the repository to here:  (First, which repo is "here"?)
I’m thinking long-term; my work should be reflected in the Code Platoon
repo, not in yours, because Code Platoon is my employer.

Could we do the forking the other way—if I get permission, I can push
changes to CodePlatoon, but you can also fork them to JoshCheek.

We might discuss this after lunch, if you get a chance.

**Comment by JoshCheek** [comment]
So, the thought is that you'd turn the names into test names, and I'd fill in the bodies with content, as we talked about on Monday and last week. Check out the [existing tests](https://github.com/JoshCheek/challenges/tree/master/spec) to see examples of what test names look like. I copied the test output into a single source, which shows just the names without the implementations, [here](https://github.com/JoshCheek/challenges_portal/blob/d9c82dfa3047db89452ca67d3e9796e4c29e4b10/db/seeds.rb#L40-L917).

---

> if the students will be testing a Ruby application, what does the application do? 

You can either define that, or scope it smaller than that. eg you don't need to write an app to show that you know how to query a database.

---

> about forking the repository to here:  (First, which repo is "here"?)

"Here" is the CodePlatoon organization, it's a response to the apprehensions you put in your email:

screenshot 2016-04-06 20 30 29

---

> Could we do the forking the other way—if I get permission, I can push changes to CodePlatoon, but you can also fork them to JoshCheek.

That isn't how git works. Eg this is what it means for git to be "distributed"

**Comment by JoshCheek** [comment]
Like you're allowed to have your repo, just like I'm allowed to have mine. None is officially the owner. You can fork it to CodePlatoon, which means that CodePlatoon has it, as I do, and you can push to CodePlatoon, but the kind thing to do is to send it back to me, too.

**Pull request closed without merging**
